/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-03-27 06:44:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.guest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import pack.product.ProductMgr;
import pack.product.ProductDto;
import java.util.ArrayList;

public final class productlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/guest/guest_bottom.jsp", Long.valueOf(1584926961323L));
    _jspx_dependants.put("/guest/guest_top.jsp", Long.valueOf(1584686489340L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("pack.product.ProductDto");
    _jspx_imports_classes.add("pack.product.ProductMgr");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      pack.product.ProductMgr productMgr = null;
      productMgr = (pack.product.ProductMgr) _jspx_page_context.getAttribute("productMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (productMgr == null){
        productMgr = new pack.product.ProductMgr();
        _jspx_page_context.setAttribute("productMgr", productMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상품목록 - 고객</title>\r\n");
      out.write("<link href=\"../css/board.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/script.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/script2.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>전문 쇼핑몰</h2>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');

	String memid = (String)session.getAttribute("idKey");
	String log = "";

	if (memid == null)
		log = "<a href='../member/login.jsp'>로그인</a>";
	else
		log = "<a href='../member/logout.jsp'>로그아웃</a>";

	String mem = "";

	if (memid == null)
		mem = "<a href='../member/register.jsp'>회원가입</a>";
	else
		mem = "<a href='../member/memberupdate.jsp'>회원수정</a>";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table style=\"width: 80%\">\r\n");
      out.write("\t<tr style=\"background-color: silver; text-align: center;\">\r\n");
      out.write("\t\t<td>");
      out.print(log);
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(mem);
      out.write("</td>\r\n");
      out.write("\t\t<td><a href=\"productlist.jsp\">상품 목록</a></td>\r\n");
      out.write("\t\t<td><a href=\"cartlist.jsp\">장바구니</a></td>\r\n");
      out.write("\t\t<td><a href=\"orderlist.jsp\">구매목록</a></td>\r\n");
      out.write("\t\t<td><a href=\"../board/boardlist.jsp\">게시판</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("\t* 고객님 지갑을 마음껏 열어주세요 *\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<table style=\"width: 80%\">\r\n");
      out.write("\t\t<tr style=\"backgroud-color: silver;\">\r\n");
      out.write("\t\t\t<th>상품명</th>\r\n");
      out.write("\t\t\t<th>가격</th>\r\n");
      out.write("\t\t\t<th>재고량</th>\r\n");
      out.write("\t\t\t<th>상세보기</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			ArrayList<ProductDto> list = productMgr.getProductAll();
			for (ProductDto p : list) {
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><img src=\"../upload/");
      out.print(p.getImage());
      out.write("\" width=\"100\"> ");
      out.print(p.getName());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(p.getPrice());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(p.getStock());
      out.write("</td>\r\n");
      out.write("\t\t\t<td><a href=\"javascript:productDetail('");
      out.print(p.getNo());
      out.write("')\">상세보기</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<hr style=\"width: 80%; float: left;\"><br>\r\n");
      out.write("<table style=\"width:80%;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><b>고객님 환영합니다. </b> (주)KIC ☎02-111-1234 담당 : 신길동</td>\r\n");
      out.write("\t\t<td style=\"text-align: right;\"><a href=\"../admin/admin_index.jsp\">관리자</a>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("\t<form action=\"productdetail_g.jsp\" name=\"detailFrm\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"no\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
