# -*- coding: utf-8 -*-
"""bj_2523.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u465SR7moqNfx6e0qy6P4zMrHRzp4BAo
"""

# ===========================================================
# 문제 2523
# 예제를 보고 규칙을 유추한 뒤에 별을 찍어 보세요.

# 입력
# 첫째 줄에 N(1 ≤ N ≤ 100)이 주어진다.

# 출력
# 첫째 줄부터 2×N-1번째 줄까지 차례대로 별을 출력한다.

# *
# **
# ***
# **
# *
# 

# ===========================================================

n = int(input())

for s in range(n): # 0 1 2
    for t in range(s+1): # 0 / 0 1 / 0 1 2
        print("*", end="")
    print()

for rs in range(n-1, 0, -1): # 2 1 
    for rt in range(rs):
        print("*", end="")
    print()

