# -*- coding: utf-8 -*-
"""bj_8958.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/172tiJO9cm9HOP89EAvOQqANCSnkUMIKi
"""

# ==============================================================================
# 문제 8958
# "OOXXOXXOOO"와 같은 OX퀴즈의 결과가 있다. O는 문제를 맞은 것이고, X는 문제를 틀린 것이다. 
# 문제를 맞은 경우 그 문제의 점수는 그 문제까지 연속된 O의 개수가 된다. 
# 예를 들어, 10번 문제의 점수는 3이 된다.

# "OOXXOXXOOO"의 점수는 1+2+0+0+1+0+0+1+2+3 = 10점이다.

# OX퀴즈의 결과가 주어졌을 때, 점수를 구하는 프로그램을 작성하시오.

# 입력
# 첫째 줄에 테스트 케이스의 개수가 주어진다. 각 테스트 케이스는 한 줄로 이루어져 있고, 
# 길이가 0보다 크고 80보다 작은 문자열이 주어진다. 문자열은 O와 X만으로 이루어져 있다.

# 출력
# 각 테스트 케이스마다 점수를 출력한다.
# ==============================================================================

case_count = int(input())
case_list = []
score_list = []

#콤보 점수 저장

for n in range(case_count):
    # OX 리스트 받기
    test_case = input()
    # OX 리스트 cases_list에 저장
    case_list.append(test_case)

for s in case_list:
    # s는 OX 리스트 이고, 문자열이다. 리스트로 변환.
    s_list = list(s)
    combo = 0
    score = 0

    # 검사하면서 O 라면 콤보점수를 하나 더하고, 그 값을 score에 더한다.
    for ox in s_list:
        if ox == 'O':
            combo = combo + 1
            score = score + combo
        # 값이 틀리면 콤보점수 초기화
        if ox == 'X':
            combo = 0

    score_list.append(score)

for result in score_list:
    print(result)

# 다른 사람의 답 ===============================================================
import sys  # 빠른 입력을 위한 모듈

N = int(sys.stdin.readline().strip())

for _ in range(N):
    test = sys.stdin.readline().strip()        # 값 입력. 
    score = 0
    tmp = 0
    # 하나하나 검사하기 
    for i in test:
        if i == 'O':        # 'O' 일 때, 연속된 O 에 가점 주는 알고리즘.  
            score += tmp + 1
            tmp += 1
        else:               # 'x' 일때 
            tmp = 0
    print(score)
# ==============================================================================

