/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-03-31 06:04:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fitness;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import pack.equip.EquipDto;
import java.util.ArrayList;

public final class fitness_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/fitness/../guest/guest_bottom.jsp", Long.valueOf(1585632956739L));
    _jspx_dependants.put("/fitness/../index_top.jsp", Long.valueOf(1585617049568L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1585116354586L));
    _jspx_dependants.put("jar:file:/C:/work/jsou/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semi_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/work/jsou/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semi_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("pack.equip.EquipDto");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      pack.equip.EquipDto equip = null;
      equip = (pack.equip.EquipDto) _jspx_page_context.getAttribute("equip", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (equip == null){
        equip = new pack.equip.EquipDto();
        _jspx_page_context.setAttribute("equip", equip, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      pack.equip.EquipProc equipProc = null;
      equipProc = (pack.equip.EquipProc) _jspx_page_context.getAttribute("equipProc", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (equipProc == null){
        equipProc = new pack.equip.EquipProc();
        _jspx_page_context.setAttribute("equipProc", equipProc, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link href=\"../css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script src=\"../js/script.js\"></script>\n");
      out.write("<link href=\"../css/imsi.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");

		String memid = (String) session.getAttribute("idkey");
		String log = "";

		if (memid == null) // 로그인 안함
			log = "<a href='../guest/login.jsp'><img src='../images/loginin.png'></a>";
		else
			log = "<a href='../guest/logout.jsp'><img src='../images/logout.png'></a>";

		String mem = "";
		if (memid == null)
			mem = "<a href='../member/register.jsp'><img src='../images/signup.png'></a>";
		else
			mem = "<a href='../reviewboard/reviewboardlist.jsp'><img src='../images/review.png'></a>";
	
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<table style=\"width: 10%\">\r\n");
      out.write(" <tr style=\"text-align:left;\">\r\n");
      out.write("\t<td>\t\r\n");
      out.write("\t\t<a href=\"../main.jsp\">\r\n");
      out.write("\t\t\t<img src=\"../images/kic.png\">\r\n");
      out.write("\t\t</a>\t\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<hr>\r\n");
      out.write("<br>");
      out.write("\n");
      out.write("\t<table style=\"width: 80%\" border=\"1\">\n");
      out.write("\t\t<tr style=\"background-color: white; text-align: center;\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<td><a href=\"../main.jsp\"><img src=\"../images/home.png\"></a></td>\n");
      out.write("\t\t\t<td>");
      out.print(log);
      out.write("</td>\n");
      out.write("\t\t\t<td>");
      out.print(mem);
      out.write("</td>\n");
      out.write("\t\t\t<td style=\"background-color: #aabbcc; text-align: center;\">\n");
      out.write("\t\t\t<a class=\"menu_1\" href=\"../fitness/fitness.jsp\"><img\n");
      out.write("\t\t\t\t\tsrc=\"../images/fitness.png\"></a></td>\n");
      out.write("\t\t\t<td><a href=\"../trainers/trainers_index.jsp\"><img\n");
      out.write("\t\t\t\t\tsrc=\"../images/trainers.png\"></a></td>\n");
      out.write("\t\t\t<td><a href=\"../programs/program_index.jsp\"><img\n");
      out.write("\t\t\t\t\tsrc=\"../images/programs.png\"></a></td>\n");
      out.write("\t\t\t<td><a href=\"../qnaboard/qnaboardlist.jsp\"><img src=\"../images/community.png\"></a></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<div class=\"fitness_info\">\n");
      out.write("\t<div style=\"width:150px\">\n");
      out.write("\t<table style=\"width: 140px\" border=\"1\">\n");
      out.write("\t\t<tr style=\"background-color: #aabbcc; text-align: center;\">\n");
      out.write("\t\t\t<td><a href=\"fitness.jsp\"> <img src=\"../images/equipment.png\">\n");
      out.write("\t\t\t</a></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr style=\"text-align: center;\">\n");
      out.write("\t\t\t<td><a href=\"location.jsp\"> <img src=\"../images/location.png\">\n");
      out.write("\t\t\t</a></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<section>\n");
      out.write("\t\t");

		ArrayList<EquipDto> list = (ArrayList<EquipDto>) equipProc.selectEquip();
	
      out.write('\n');
      out.write('	');
      out.write('	');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /fitness/fitness.jsp(75,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("list");
        // /fitness/fitness.jsp(75,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(list);
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write('\n');
      out.write('	');
      out.write('	');
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /fitness/fitness.jsp(76,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("e");
        // /fitness/fitness.jsp(76,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(list);
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\n");
              out.write("\t\t\t<figure>\n");
              out.write("\t\t\t\t<a href=\"equipdetail.jsp?no=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.equip_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\"><img src=\"../upload/");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.equip_image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" width=\"250\" height=\"250\">\n");
              out.write("\t\t\t\t</a>\n");
              out.write("\t\t\t\t<figcaption><a href=\"equipdetail.jsp?no=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.equip_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write('"');
              out.write('>');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.equip_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</a></figcaption>\n");
              out.write("\t\t\t</figure>\n");
              out.write("\t\t");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\n");
      out.write("\t\t</section>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t</div>\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("<hr style=\"width: 100%; float: center;\">\r\n");
      out.write("<br>\r\n");
      out.write("<table style=\"width: 80%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"text-aligns: center;\">\r\n");
      out.write("\t\t(주)KIC ☎02-111-1234 담당 : 근손실\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td style=\"text-aligns: right;\">\r\n");
      out.write("\t\t\t<a href=\"../admin_index.jsp\"><img src=\"../images/add.png\" alt=\"ManagerPage\"></a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
